# Powerlevel10k Catppuccin-like theme (modifié)
typeset -g POWERLEVEL9K_MODE=nerdfont-complete
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir vcs)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time node_version php_version python_version time)

# Symboles et format
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%F{242}↳%f '
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='❯ '

# OS icon
typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=''

# Couleurs Catppuccin (Mocha)
typeset -g POWERLEVEL9K_BACKGROUND=NONE
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=0
typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=255
typeset -g POWERLEVEL9K_DIR_FOREGROUND=255
typeset -g POWERLEVEL9K_DIR_BACKGROUND=61
typeset -g POWERLEVEL9K_TIME_FOREGROUND=240
typeset -g POWERLEVEL9K_TIME_BACKGROUND=254
typeset -g POWERLEVEL9K_STATUS_FOREGROUND=160
typeset -g POWERLEVEL9K_STATUS_BACKGROUND=235
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=178
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=235
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=70
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=236
typeset -g POWERLEVEL9K_VCS_DIRTY_FOREGROUND=166
typeset -g POWERLEVEL9K_VCS_DIRTY_BACKGROUND=236

# Git
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '

# Exécution longue
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=1
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1

# Heure
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true
