# Path to Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins
plugins=(
  git
  z
  sudo
  history
  fzf
  colored-man-pages
  command-not-found
  web-search
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Load zoxide (fast directory jumping)
eval "$(zoxide init zsh)"

# User configuration
export EDITOR='nano'

# Aliases
alias ll='ls -lah'
alias gs='git status'
alias gp='git pull'
alias gc='git commit'
alias ..='cd ..'
alias ...='cd ../..'

# Node.js, PHP, Python version display (used by Powerlevel10k)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status command_execution_time node_version php_version python_version time
)

# Enable Powerlevel10k config if available
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
